### ISSUE TITLE
Database best practice

### ISSUE THREAD

**Issue by stact** [totaljs/emptyproject-restservice#2]
For this empty project, how to transform this nosql database with mongodb/mongoose purpose?
In fact, model and controller are well formed and easy to maintain (good job!). But I'm wondering to translate this with mongoose

/config 

```
database: mongodb://<your connection string>
```

/controllers/users.js (no changes)

/models/user.js (??? how to proceed here? ) 

``` javascript
var mongoose = require('mongoose');
NEWSCHEMA('User').make(function(schema) {
    // how to declare schema? Is it right?
    var userSchema = mongoose.Schema({ alias: String, created: Date });
    schema = mongoose.model('user', userSchema); // setSave, setQuery, setRemove etc.: not available

    schema.setSave(function(error, model, options, callback) {
        // how to crud with our mongoose? model.save?
    });
```

Thank you for your help on this purpose.

**Comment by petersirka** [comment]
Hi @stact,
why do you want to use Mongoose? I need this information.

**Comment by stact** [comment]
For me Mongoose allow an intuitive abstraction  model easy to implement for example to declare a sub-document: http://mongoosejs.com/docs/subdocs.html
Mongoose offers a good way to prevent wrong data.

Maybe it's not a good solution, but I'm just learning for challenge and this solution appears to be more intuitive if somebody would like to work with mongodb :)

That's why I'm trying to consolidate those two solutions (your total.js controller structure, and mongoose)

**Comment by petersirka** [comment]
OK. So:
1. don't use schema with Mongoose because Mongoose has own implementation

**Create definition e.g. `/databases/database.js`**:

``` javascript
F.database = require('mongoose');
F.database.connect(F.config.database);
```

**Update your app config**:

``` html
database              : mongodb://localhost/test/connetion-string-to-database
```

**Update your model `/models/user.js`**:

``` javascript
// Save your model as a global variable (you saves a lot characters in the source-code)
global.User = F.database.model('User', { alias: String, created: Date });
```

**Usage in controller**:

``` javascript
exports.install = function() {
    F.route('/api/users/', json_users_create, ['post']);
};

function json_users_create() {
   var self = this;
   // self.body --> contains data from client-side
   var user = new User(self.body);
   user.save(function(err, response) {
       if (err)
           return self.json({ error: err });
       self.json(response);
   });
}
```

I recommend to use `SQLAgent` https://github.com/totaljs/node-sqlagent because it's very good and works with PostgreSQL, SQL Server, MySQL and MongoDB too 👍 

Good luck!

**Comment by stact** [comment]
Oh okay my bad, I thought we could find a way to reach this goal.
I will take a look to SQLAgent, it seems a good alternative. Thank you Peter! As usual you're the best!

**Comment by petersirka** [comment]
Good way! Let me know if you need help.

**Comment by stact** [comment]
I'm trying to implement your solution above, and it seems that "/databases/database.js" is never triggered (maybe because is for nosql solution).

Then I moved this file under "/definitions/database.js", but here it seems that "/models/xxx.js" launch before "/definitions/xxx.js" and an issue occurs because the model doesn't know F.database.model

In the documentation I see that the folders are executed with this following steps:

```
Initialization: Modules --> Packages --> Models --> Themes --> Definitions --> Controllers
```

Here what is the best practice? Create a package? Declare F.database on Models (ex: "/models/_init.js")? Change the order of folder execution (if it's possible and how?)?

Thank you again for your light!

**Comment by petersirka** [comment]
I forgot on it.. Please create a model e.g. database instead of definition (as you meant).
Thank you!
